In [1]:
import numpy as np

Attributes of a numpy array

Generate a 3x5 matrix of 15 contiguous elements. numpy.arrange takes 3 arguments ; start, stop, stepsize

In [2]:
narr = np.arange(0,30,2).reshape(3,5)
narr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

ndarray.shape = the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a
matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number
of axes, ndim.

In [3]:
narr.shape

(3, 5)

ndarray.size = the total number of elements of the array. This is equal to the product of the elements of shape.

In [4]:
narr.size

15

ndarray.dtype = an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python
types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some
examples.

In [5]:
narr.dtype

dtype('int64')

ndarray.itemsize = the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize
8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.
itemsize.

In [6]:
narr.itemsize

8

ndarray.data = the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we
will access the elements in an array using indexing facilities.

In [7]:
narr.data

Get Python Type of Numpy Array

In [8]:
print(type(narr))

<class 'numpy.ndarray'>


Creating Numpy Array

In [9]:
narr1 = np.array([1,2,3,4,5])
print(narr1)
print(narr1.dtype)

[1 2 3 4 5]
int64


In [10]:
narr1 = np.array([1.0,2.5,3.7,4.6,5.7])
print(narr1)
print(narr1.dtype)

[1.  2.5 3.7 4.6 5.7]
float64


In [11]:
narr2 = np.array([[1.5, 2, 3], [4, 5, 6]])
narr2

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [12]:
narr3 = np.array([[1, 2], [3, 4]], dtype=complex)
narr3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to
create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.
The function zeros creates an array full of zeros, the function ones creates an array full of ones, and the function
empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype
of the created array is float64, but it can be specified via the key word argument dtype.

In [13]:
narr4 = np.zeros((3, 4))
narr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
narr5 = np.ones((2, 3, 4), dtype=np.int8)
narr5

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int8)

In [15]:
narr6 = np.empty((2, 3))
narr6

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements
obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that
receives as an argument the number of elements that we want, instead of the step:

In [16]:
narr7 = np.linspace(0, 2, 9)
narr7

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
narr8 = np.zeros_like(narr7)
narr8

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
narr9 = np.random.rand(5,5)
narr9

array([[0.6470572 , 0.1073702 , 0.2552646 , 0.7999097 , 0.88838568],
       [0.25946394, 0.73911734, 0.67360009, 0.68105323, 0.47414588],
       [0.88313375, 0.9766036 , 0.19305138, 0.59126056, 0.2936578 ],
       [0.41157196, 0.63690425, 0.81564428, 0.68842225, 0.15509192],
       [0.82292028, 0.58002841, 0.40260551, 0.93632778, 0.17749774]])

numpy.c_ = Translates slice objects to concatenation along the second axis

In [19]:
narr10 = np.c_[np.array([1,2,3]), np.array([4,5,6])]
narr10

array([[1, 4],
       [2, 5],
       [3, 6]])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])